name: NiNeDesign
favicon: null
layout_spectrum: 0.9825876289978623
typography_spectrum: 0.7745564843062311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#2f2f2f'
    - '#7a7a7a'
    - '#c6c6c6'
  brandStrength: 0.6875
  lightness: 0.7156412170734257
  saturation: 0.020348884630948305
  rhythmicContrast: 0.871744477422908
purpose: []
