name: NiNeDesign
favicon: null
layout_spectrum: 0.9825876289978623
typography_spectrum: 0.7745564843062311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6515364618971944
  lightness: 0.7156412170734257
  saturation: 0.020348884630948305
  rhythmicContrast: 0.871744477422908
purpose: []
