name: NiNeDesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24961
title: NiNe Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#7a7a7a'
    - '#363636'
    - '#bbbbbb'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
