name: NiNeDesign
favicon: null
layout_spectrum: 0.9825876289978623
typography_spectrum: 0.7745564843062311
title: NiNe Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6f6f6f'
    - '#555555'
    - '#000000'
    - '#404040'
  brandStrength: 0.6875
  lightness: 0.7156412170734257
  saturation: 0.020348884630948305
  rhythmicContrast: 0.871744477422908
purpose: []
